service: api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

  stage: dev
  region: us-east-1

environment:
  DB_HOST: task-management.cczbfcrhtkfl.us-east-1.rds.amazonaws.com
  DB_PORT: 3306
  DB_NAME: task_management
  DB_USER: root
  DB_PWD: rootroot

functions:
  api-version:
    handler: dist/api/handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
#    environment:
#      variable2: value2

#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
